import { Product, Category } from "../types";

export const DEFAULT_CATEGORIES: Category[] = [
  { id: "1", name: "কৃত্তিক চাকের মধু" },
  { id: "2", name: "বিভিন্ন ফুলের মধু" },
  { id: "3", name: "গাওয়া ঘি" },
  { id: "4", name: "সরিষার তেল" },
  { id: "5", name: "খেজুরের গুড়" },
  { id: "6", name: "আখের গুড়" },
  { id: "7", name: "রসালো লিচু" },
  { id: "8", name: "খাঁটি আম" },
];

export const DEFAULT_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "প্রাকৃতিক কৃত্তিক চাকের খাঁটি মধু (Wild Forest Krittik Raw Honey)",
    price: 1150,
    originalPrice: 1400,
    discount: 18,
    stock: 50,
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&h=500&fit=crop",
    category: "কৃত্তিক চাকের মধু",
    isTrending: true,
    description: "সুন্দরবন ও প্রাকৃতিক বনজ অরণ্যের কৃত্তিক চাক থেকে সরাসরি সংগৃহীত ১০০% কাঁচা, অপরিশোধিত ও প্রিজারভেটিভমুক্ত খাঁটি মধু।",
    variants: [
      { id: "v1", name: "৫০০ গ্রাম", size: "500g", stock: 30, image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&h=500&fit=crop" },
      { id: "v2", name: "১ কেজি", size: "1kg", stock: 20, image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&h=500&fit=crop" },
    ],
  },
  {
    id: "p2",
    name: "সুন্দরবনের খলিসা ও বিভিন্ন ফুলের খাঁটি মধু (Sundarbans Multi-Floral Honey)",
    price: 950,
    originalPrice: 1200,
    discount: 21,
    stock: 65,
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&h=500&fit=crop",
    category: "বিভিন্ন ফুলের মধু",
    isTrending: true,
    description: "খলিসা, বাইন, গরান ও প্রাকৃতিক ঋতুভিত্তিক বিভিন্ন ফুলের নির্যাস থেকে মৌমাছির তৈরি শতভাগ খাঁটি ও সুস্বাদু প্রাকৃতিক মধু।",
    variants: [
      { id: "v1", name: "৫০০ গ্রাম", size: "500g", stock: 35, image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&h=500&fit=crop" },
      { id: "v2", name: "১ কেজি", size: "1kg", stock: 30, image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&h=500&fit=crop" },
    ],
  },
  {
    id: "p3",
    name: "প্রাকৃতিক লিচু ও সরিষা ফুলের খাঁটি মধু (Pure Litchi & Mustard Flower Honey)",
    price: 750,
    originalPrice: 950,
    discount: 21,
    stock: 55,
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&h=500&fit=crop",
    category: "বিভিন্ন ফুলের মধু",
    isTrending: false,
    description: "লিচুর বাগান ও হলুদ সরিষা ফুলের মাঠ থেকে সংগৃহীত মিষ্টি সুবাসযুক্ত হালকা ও তরল ১০০% প্রাকৃতিক মধু।",
    variants: [
      { id: "v1", name: "৫০০ গ্রাম", size: "500g", stock: 30, image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&h=500&fit=crop" },
      { id: "v2", name: "১ কেজি", size: "1kg", stock: 25, image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&h=500&fit=crop" },
    ],
  },
  {
    id: "p4",
    name: "ঐতিহ্যবাহী খাঁটি দানাদার গাওয়া ঘি (Pure Homemade Danadar Gawa Ghee)",
    price: 1450,
    originalPrice: 1800,
    discount: 19,
    stock: 45,
    image: "https://images.unsplash.com/photo-1631451095765-2c91616fc9e6?w=500&h=500&fit=crop",
    category: "গাওয়া ঘি",
    isTrending: true,
    description: "খাঁটি দেশি গরুর দুধের জ্বাল দেওয়া মাখন থেকে ঐতিহ্যবাহী পদ্ধতিতে তৈরি সুবাসিত ও দানাদার খাঁটি গাওয়া ঘি।",
    variants: [
      { id: "v1", name: "৫০০ গ্রাম", size: "500g", stock: 25, image: "https://images.unsplash.com/photo-1631451095765-2c91616fc9e6?w=500&h=500&fit=crop" },
      { id: "v2", name: "১ কেজি", size: "1kg", stock: 20, image: "https://images.unsplash.com/photo-1631451095765-2c91616fc9e6?w=500&h=500&fit=crop" },
    ],
  },
  {
    id: "p5",
    name: "কাঠের ঘানি ভাঙা ১০০% খাঁটি সরিষার তেল (Pure Cold Pressed Mustard Oil)",
    price: 360,
    originalPrice: 450,
    discount: 20,
    stock: 80,
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&h=500&fit=crop",
    category: "সরিষার তেল",
    isTrending: true,
    description: "ঐতিহ্যবাহী কাঠের ঘানিতে কোল্ড প্রেস পদ্ধতিতে ভাঙানো ঝাঁঝালো ও শতভাগ খাঁটি দেশি সরিষার তেল।",
    variants: [
      { id: "v1", name: "১ লিটার", size: "1L", stock: 50, image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&h=500&fit=crop" },
      { id: "v2", name: "৫ লিটার (ফ্যামিলি প্যাক)", size: "5L", stock: 30, image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&h=500&fit=crop" },
    ],
  },
  {
    id: "p6",
    name: "যশোরের খাঁটি দানাদার খেজুরের পাটালি গুড় (Pure Date Palm Patali Jaggery)",
    price: 480,
    originalPrice: 600,
    discount: 20,
    stock: 60,
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=500&h=500&fit=crop",
    category: "খেজুরের গুড়",
    isTrending: true,
    description: "যশোরের ঐতিহ্যবাহী তাজা খেজুরের রস থেকে তৈরি সুস্বাদু, সুবাসিত ও কোনো চিনি বা কেমিক্যাল ছাড়া খাঁটি দানাদার পাটালি গুড়।",
    variants: [
      { id: "v1", name: "১ কেজি", size: "1kg", stock: 35, image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=500&h=500&fit=crop" },
      { id: "v2", name: "২ কেজি", size: "2kg", stock: 25, image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=500&h=500&fit=crop" },
    ],
  },
  {
    id: "p7",
    name: "ঐতিহ্যবাহী নলেন খেজুরের তরল ঝোলা গুড় (Pure Liquid Nolen Date Gur)",
    price: 420,
    originalPrice: 550,
    discount: 24,
    stock: 45,
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&h=500&fit=crop",
    category: "খেজুরের গুড়",
    isTrending: false,
    description: "খেজুরের তাজা রস জ্বাল দিয়ে তৈরি পিঠা-পায়েস ও নাস্তার জন্য অতুলনীয় স্বাদের খাঁটি নলেন ঝোলা গুড়।",
    variants: [
      { id: "v1", name: "১ কেজি বয়াম", size: "1kg", stock: 25, image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&h=500&fit=crop" },
      { id: "v2", name: "২ কেজি বয়াম", size: "2kg", stock: 20, image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&h=500&fit=crop" },
    ],
  },
  {
    id: "p8",
    name: "শতভাগ খাঁটি দেশি আখের গুড় (Pure Sugarcane Jaggery)",
    price: 320,
    originalPrice: 400,
    discount: 20,
    stock: 70,
    image: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=500&h=500&fit=crop",
    category: "আখের গুড়",
    isTrending: true,
    description: "টাটকা দেশি আখের রস জ্বাল দিয়ে তৈরি সম্পূর্ণ কেমিক্যাল ও হাইড্রোজমুক্ত দানাদার সুস্বাদু খাঁটি আখের গুড়।",
    variants: [
      { id: "v1", name: "১ কেজি", size: "1kg", stock: 40, image: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=500&h=500&fit=crop" },
      { id: "v2", name: "২ কেজি", size: "2kg", stock: 30, image: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=500&h=500&fit=crop" },
    ],
  },
  {
    id: "p9",
    name: "দিনাজপুরের প্রিমিয়াম রসালো বেদানা ও বোম্বাই লিচু (Fresh Dinajpur Juicy Litchi)",
    price: 850,
    originalPrice: 1100,
    discount: 23,
    stock: 50,
    image: "https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=500&h=500&fit=crop",
    category: "রসালো লিচু",
    isTrending: true,
    description: "দিনাজপুরের বিখ্যাত বাগান থেকে সরাসরি সংগ্রহকৃত ফরমালিনমুক্ত টসটসে মিষ্টি ও রসালো প্রিমিয়াম লিচু।",
    variants: [
      { id: "v1", name: "১০০ পিস ক্যারেট", size: "100 pcs", stock: 30, image: "https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=500&h=500&fit=crop" },
      { id: "v2", name: "২০০ পিস ক্যারেট", size: "200 pcs", stock: 20, image: "https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=500&h=500&fit=crop" },
    ],
  },
  {
    id: "p10",
    name: "রাজশাহীর মিষ্টি হিমসাগর ও ল্যাংড়া আম (Chemical-Free Rajshahi Mangoes)",
    price: 1250,
    originalPrice: 1500,
    discount: 17,
    stock: 45,
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=500&h=500&fit=crop",
    category: "খাঁটি আম",
    isTrending: true,
    description: "গাছপাকা ফরমালিন ও কার্বাইডমুক্ত শতভাগ নিরাপদ, মিষ্টি ও সুস্বাদু রাজশাহীর সেরা জাতের আম।",
    variants: [
      { id: "v1", name: "১০ কেজি ক্যারেট", size: "10kg", stock: 25, image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=500&h=500&fit=crop" },
      { id: "v2", name: "২০ কেজি ক্যারেট", size: "20kg", stock: 20, image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=500&h=500&fit=crop" },
    ],
  },
  {
    id: "p11",
    name: "প্রিমিয়াম এনার্জি হানি নাট (Premium Honey Nut with 12+ Dry Fruits)",
    price: 850,
    originalPrice: 1100,
    discount: 23,
    stock: 70,
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=500&h=500&fit=crop",
    category: "বিভিন্ন ফুলের মধু",
    isTrending: true,
    isPublished: true,
    description: "কাঠবাদাম, কাজুবাদাম, পেস্তা বাদাম, আখরোট, ড্রাই ফ্রুটস এবং খাঁটি সুন্দরবনের মধুর সংমিশ্রণে তৈরি স্বাস্থ্যকর এনার্জি বুস্টার।",
    variants: [
      { id: "v1", name: "৫০০ গ্রাম", size: "500g", stock: 40, image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=500&h=500&fit=crop" },
      { id: "v2", name: "১ কেজি", size: "1kg", stock: 30, image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=500&h=500&fit=crop" },
    ],
  },
  {
    id: "p12",
    name: "কোল্ড প্রেসড খাঁটি কালোজিরা তেল (Pure Cold-Pressed Black Seed Oil)",
    price: 450,
    originalPrice: 550,
    discount: 18,
    stock: 50,
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&h=500&fit=crop",
    category: "সরিষার তেল",
    isTrending: true,
    isPublished: true,
    description: "ফার্স্ট প্রেস খাঁটি কালোজিরা থেকে তৈরি কোনো প্রকার হিট ছাড়া প্রাকৃতিক গুণাগুণ অক্ষুণ্ণ রাখা শতভাগ খাঁটি তেল।",
    variants: [
      { id: "v1", name: "১০০ মিলি", size: "100ml", stock: 30, image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&h=500&fit=crop" },
      { id: "v2", name: "২৫০ মিলি", size: "250ml", stock: 20, image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&h=500&fit=crop" },
    ],
  },
];

export const DEFAULT_BANNERS = [
  {
    id: 1,
    title: "১০০% প্রাকৃতিক সুন্দরবনের খাঁটি মধু ও প্রিমিয়াম হানি নাট",
    subtitle: "সরাসরি বন ও বাগান থেকে সংগৃহীত অপরিশোধিত খাঁটি মধু — রকমারি পণ্য হাড়ি",
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=1600&h=600&fit=crop",
    type: "hero",
  },
  {
    id: 2,
    title: "কাঠের ঘানি ভাঙা খাঁটি সরিষার তেল ও সুবাসিত দানাদার গাওয়া ঘি",
    subtitle: "আসল ঘ্রাণ ও খাঁটি গ্রামীণ স্বাদ আপনার পরিবারের সুস্বাস্থ্যে শতভাগ নিরাপদ",
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=1600&h=600&fit=crop",
    type: "hero",
  },
  {
    id: 3,
    title: "মদিনার খাঁটি মরিয়ম খেজুর, অর্গানিক চিয়া সিড ও কোল্ড প্রেসড কালোজিরা তেল",
    subtitle: "প্রাকৃতিক পুষ্টিগুণে ভরপুর সেরা অর্গানিক খাদ্যপণ্য — ক্যাশ অন ডেলিভারি সুবিধা",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=1600&h=600&fit=crop",
    type: "hero",
  },
  {
    id: 4,
    title: "মধু + ঘি + সরিষার তেল স্পেশাল কম্বো প্যাক",
    subtitle: "একসাথে ৩টি খাঁটি খাদ্যপণ্য কিনুন বিশেষ ছাড়ে",
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&h=500&fit=crop",
    type: "right_top",
  },
  {
    id: 5,
    title: "প্রিমিয়াম হানি নাট ও মরিয়ম খেজুর কম্বো প্যাক",
    subtitle: "প্রাকৃতিক এনার্জি ও পুষ্টির সেরা কম্বিনেশন",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800&h=500&fit=crop",
    type: "right_bottom",
  },
  {
    id: 6,
    title: "১০০% বিশুদ্ধ ও প্রাকৃতিক খাদ্যপণ্যের নির্ভরযোগ্য প্রতিষ্ঠান",
    subtitle: "সারা বাংলাদেশে দ্রুততম হোম ডেলিভারি ও শতভাগ ক্যাশ অন ডেলিভারি",
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=1600&h=450&fit=crop",
    type: "secondary",
  }
];

export const BENGALI_FONTS = [
  { name: "Default (Hind Siliguri)", value: "font-sans" },
  { name: "Lalsalu (Anek Bangla)", value: "font-lalsalu" },
  { name: "Ador (Mina)", value: "font-ador" },
  { name: "Galada (Stylized)", value: "font-galada" },
  { name: "Atma (Playful)", value: "font-atma" },
  { name: "Tiro Bangla (Serif)", value: "font-tiro" },
  { name: "Noto Sans (Clean)", value: "font-noto" },
  { name: "Baloo Da 2 (Rounded)", value: "font-baloo" },
  { name: "Sulaiman Lipi", value: "font-sulaiman" },
];

export const NOTIF_SOUND_URL = "https://assets.mixkit.co/active_storage/sfx/2874/2874-preview.mp3";

export const MASTER_EMAILS = [
  "rokomariponnohari@gmail.com",
  "bonieaminrony@gmail.com",
  "islamicsoktitv@gmail.com",
  "rokomariponnohari@gmail.com",
  "ifilmbd2025@gmail.com",
];

export const districtThanaMap: Record<string, string[]> = {
  "Bagerhat": ["Bagerhat Sadar", "Chitalmari", "Fakirhat", "Kachua", "Mollahat", "Mongla", "Morrelganj", "Rampal", "Sarankhola"],
  "Bandarban": ["Alikadam", "Bandarban Sadar", "Lama", "Naikhongchhari", "Rowangchhari", "Ruma", "Thanchi"],
  "Barguna": ["Amtali", "Bamna", "Barguna Sadar", "Betagi", "Patharghata", "Taltali"],
  "Barishal": ["Agailjhara", "Airport", "Babuganj", "Bakerganj", "Banaripara", "Bandar", "Barishal Sadar", "Gournadi", "Hizla", "Kaunia", "Kotwali", "Mehendiganj", "Muladi", "Wazirpur"],
  "Bhola": ["Bhola Sadar", "Burhanuddin", "Char Fasson", "Daulatkhan", "Lalmohan", "Manpura", "Tazumuddin"],
  "Bogura": ["Adamdighi", "Bogura Sadar", "Dhunat", "Dupchanchia", "Gabtali", "Kahaloo", "Nandigram", "Sariakandi", "Shajahanpur", "Sherpur", "Shibganj", "Sonatala"],
  "Brahmanbaria": ["Akhaura", "Ashuganj", "Bancharampur", "Bijoynagar", "Brahmanbaria Sadar", "Kasba", "Nabinagar", "Nasirnagar", "Sarail"],
  "Chandpur": ["Chandpur Sadar", "Faridganj", "Haimchar", "Hajiganj", "Kachua", "Matlab Dakkhin", "Matlab Uttar", "Shahrasti"],
  "Chapainawabganj": ["Bholahat", "Chapainawabganj Sadar", "Gomastapur", "Nachole", "Shibganj"],
  "Chattogram": ["Akbarshah", "Anwara", "Bakalia", "Bandar", "Banshkhali", "Bayazid Bostami", "Boalkhali", "Chandanaish", "Chandgaon", "Chawkbazar", "Double Mooring", "EPZ", "Fatikchhari", "Halishahar", "Hathazari", "Karnaphuli", "Khulshi", "Kotwali", "Lohagara", "Mirsharai", "Pahartali", "Panchlaish", "Patenga", "Patiya", "Rangunia", "Raozan", "Sadarghat", "Sandwip", "Satkania", "Sitakunda"],
  "Chuadanga": ["Alamdanga", "Chuadanga Sadar", "Damurhuda", "Jibannagar"],
  "Cox's Bazar": ["Chakaria", "Cox's Bazar Sadar", "Eidgaon", "Kutubdia", "Maheshkhali", "Pekua", "Ramu", "Teknaf", "Ukhiya"],
  "Cumilla": ["Barura", "Brahmanpara", "Burichang", "Chandina", "Chauddagram", "Cumilla Adarsha Sadar", "Cumilla Sadar South", "Daudkandi", "Debidwar", "Homna", "Laksam", "Lalmai", "Meghna", "Monohargonj", "Muradnagar", "Nangalkot", "Titas"],
  "Dhaka": ["Adabor", "Badda", "Banani", "Bangshal", "Bhashantek", "Bhatara", "Cantonment", "Chawkbazar", "Dakshinkhan", "Darus Salam", "Demra", "Dhamrai", "Dhanmondi", "Dohar", "Gendaria", "Gulshan", "Hatirjheel", "Hazaribagh", "Jatrabari", "Kadamtali", "Kafrul", "Kalabagan", "Kamrangirchar", "Keraniganj", "Khilgaon", "Khilkhet", "Kotwali", "Lalbagh", "Mirpur", "Mohammadpur", "Motijheel", "Nawabganj", "New Market", "Pallabi", "Paltan", "Ramna", "Rampura", "Rupnagar", "Sabujbagh", "Savar", "Shah Ali", "Shahbag", "Sher-e-Bangla Nagar", "Shyampur", "Sutrapur", "Tejgaon", "Turag", "Uttara", "Uttarkhan", "Vatara", "Wari"],
  "Dinajpur": ["Birampur", "Birganj", "Biral", "Bochaganj", "Chirirbandar", "Dinajpur Sadar", "Ghoraghat", "Hakimpur", "Kaharole", "Khansama", "Nawabganj", "Parbatipur", "Phulbari"],
  "Faridpur": ["Alfadanga", "Bhanga", "Boalmari", "Charbhadrasan", "Faridpur Sadar", "Madhukhali", "Nagarkanda", "Sadarpur", "Saltha"],
  "Feni": ["Chhagalnaiya", "Daganbhuiyan", "Feni Sadar", "Fulgazi", "Parshuram", "Sonagazi"],
  "Gaibandha": ["Gaibandha Sadar", "Gobindaganj", "Palashbari", "Phulchhari", "Sadullapur", "Saghata", "Sundarganj"],
  "Gazipur": ["Bason", "Gacha", "Gazipur Sadar", "Kaliakair", "Kaliganj", "Kapasia", "Kashimpur", "Konabari", "Pubail", "Sreepur", "Tongi"],
  "Gopalganj": ["Gopalganj Sadar", "Kashiani", "Kotalipara", "Muksudpur", "Tungipara"],
  "Habiganj": ["Ajmiriganj", "Bahubal", "Baniachong", "Chunarughat", "Habiganj Sadar", "Lakhai", "Madhabpur", "Nabiganj", "Shaistagonj"],
  "Jamalpur": ["Baksiganj", "Dewanganj", "Islampur", "Jamalpur Sadar", "Madarganj", "Melandaha", "Sarishabari"],
  "Jashore": ["Abhaynagar", "Bagherpara", "Chaugachha", "Jashore Sadar", "Jhikargachha", "Keshabpur", "Manirampur", "Sharsha"],
  "Jhalokati": ["Jhalokati Sadar", "Kathalia", "Nalchity", "Rajapur"],
  "Jhenaidah": ["Harinakundu", "Jhenaidah Sadar", "Kaliganj", "Kotchandpur", "Maheshpur", "Shailkupa"],
  "Joypurhat": ["Akkelpur", "Joypurhat Sadar", "Kalai", "Khetlal", "Panchbibi"],
  "Khagrachhari": ["Dighinala", "Guimara", "Khagrachhari Sadar", "Lakshmichhari", "Mahalchhari", "Manikchhari", "Matiranga", "Panchhari", "Ramgarh"],
  "Khulna": ["Aranghata", "Batiaghata", "Dacope", "Daulatpur", "Dighalia", "Dumuria", "Harintana", "Khalishpur", "Khan Jahan Ali", "Khulna Sadar", "Koyra", "Labanchara", "Paikgachha", "Phultala", "Rupsha", "Sonadanga", "Terokhada"],
  "Kishoreganj": ["Austagram", "Bajitpur", "Bhairab", "Hossainpur", "Itna", "Karimganj", "Katiadi", "Kishoreganj Sadar", "Kuliarchar", "Mithamain", "Nikli", "Pakundia", "Tarail"],
  "Kurigram": ["Bhurungamari", "Char Rajibpur", "Chilmari", "Kurigram Sadar", "Nageshwari", "Phulbari", "Rajarhat", "Rowmari", "Ulipur"],
  "Kushtia": ["Bheramara", "Daulatpur", "Khoksa", "Kumarkhali", "Kushtia Sadar", "Mirpur"],
  "Lakshmipur": ["Kamalnagar", "Lakshmipur Sadar", "Raipur", "Ramganj", "Ramgati"],
  "Lalmonirhat": ["Aditmari", "Hatibandha", "Kaliganj", "Lalmonirhat Sadar", "Patgram"],
  "Madaripur": ["Dasar", "Kalkini", "Madaripur Sadar", "Rajoir", "Shibchar"],
  "Magura": ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
  "Manikganj": ["Daulatpur", "Ghior", "Harirampur", "Manikganj Sadar", "Saturia", "Shibalaya", "Singair"],
  "Meherpur": ["Gangni", "Meherpur Sadar", "Mujibnagar"],
  "Moulvibazar": ["Barlekha", "Juri", "Kamalganj", "Kulaura", "Moulvibazar Sadar", "Rajnagar", "Sreemangal"],
  "Munshiganj": ["Gazaria", "Lohajang", "Munshiganj Sadar", "Sirajdikhan", "Sreenagar", "Tongibari"],
  "Mymensingh": ["Bhaluka", "Dhobaura", "Fulbaria", "Gafargaon", "Gouripur", "Haluaghat", "Ishwarganj", "Muktagachha", "Mymensingh Sadar", "Nandail", "Pagla", "Phulpur", "Tarakanda", "Trishal"],
  "Naogaon": ["Atrai", "Badalgachhi", "Dhamoirhat", "Manda", "Mohadevpur", "Naogaon Sadar", "Niamatpur", "Patnitala", "Porsha", "Raninagar", "Sapahar"],
  "Narail": ["Kalia", "Lohagara", "Narail Sadar"],
  "Narayanganj": ["Araihazar", "Bandar", "Fatullah", "Narayanganj Sadar", "Rupganj", "Siddhirganj", "Sonargaon"],
  "Narsingdi": ["Belabo", "Monohardi", "Narsingdi Sadar", "Palash", "Raipura", "Shibpur"],
  "Natore": ["Bagatipara", "Baraigram", "Gurudaspur", "Lalpur", "Naldanga", "Natore Sadar", "Singra"],
  "Netrokona": ["Atpara", "Barhatta", "Durgapur", "Kalmakanda", "Kendua", "Khaliajuri", "Madan", "Mohanganj", "Netrokona Sadar", "Purbadhala"],
  "Nilphamari": ["Dimla", "Domar", "Jaldhaka", "Kishoreganj", "Nilphamari Sadar", "Saidpur"],
  "Noakhali": ["Begumganj", "Chatkhil", "Companiganj", "Hatia", "Kabirhat", "Noakhali Sadar", "Senbug", "Sonaimuri", "Subarnachar"],
  "Pabna": ["Atgharia", "Bera", "Bhangura", "Chatmohar", "Faridpur", "Ishwardi", "Pabna Sadar", "Santhia", "Sujanagar"],
  "Panchagarh": ["Atwari", "Boda", "Debiganj", "Panchagarh Sadar", "Tetulia"],
  "Patuakhali": ["Bauphal", "Dashmina", "Dumki", "Galachipa", "Kalapara", "Mirzaganj", "Patuakhali Sadar", "Rangabali"],
  "Pirojpur": ["Bhandaria", "Kaukhali", "Mathbaria", "Nazirpur", "Nesarabad", "Pirojpur Sadar", "Zianagar"],
  "Rajbari": ["Baliakandi", "Goalanda", "Kalukhali", "Pangsha", "Rajbari Sadar"],
  "Rajshahi": ["Airport", "Bagha", "Bagmara", "Belpukur", "Boalia", "Chandrima", "Charghat", "Damkura", "Durgapur", "Godagari", "Karnahar", "Kashiadanga", "Katakhali", "Mohanpur", "Motihar", "Paba", "Puthia", "Rajpara", "Rajshahi Sadar", "Shah Makhdum", "Tanore"],
  "Rangamati": ["Bagaichhari", "Barkal", "Belaichhari", "Juraichhari", "Kaptai", "Kawkhali", "Langadu", "Naniarchar", "Rajasthali", "Rangamati Sadar"],
  "Rangpur": ["Badarganj", "Gangachara", "Haragach", "Hazirhat", "Kaunia", "Kotwali", "Mahiganj", "Mithapukur", "Parshuram", "Pirgachha", "Pirganj", "Rangpur Sadar", "Tajhat", "Taraganj"],
  "Satkhira": ["Assasuni", "Debhata", "Kalaroa", "Kaliganj", "Satkhira Sadar", "Shyamnagar", "Tala"],
  "Shariatpur": ["Bhedarganj", "Damudya", "Gosairhat", "Jajira", "Naria", "Shariatpur Sadar"],
  "Sherpur": ["Jhenaigati", "Nakla", "Nalitabari", "Sherpur Sadar", "Sreebardi"],
  "Sirajganj": ["Belkuchi", "Chauhali", "Kamarkhanda", "Kazipur", "Raiganj", "Shahjadpur", "Sirajganj Sadar", "Tarash", "Ullapara"],
  "Sunamganj": ["Bishwambarpur", "Chhatak", "Derai", "Dharmapasha", "Dowarabazar", "Jagannathpur", "Jamalganj", "Madhyanagar", "Shalla", "Shanthiganj", "Sunamganj Sadar", "Tahirpur"],
  "Sylhet": ["Airport", "Balaganj", "Beanibazar", "Bishwanath", "Companiganj", "Dakshin Surma", "Fenchuganj", "Golapganj", "Gowainghat", "Jaintiapur", "Jalalabad", "Kanaighat", "Kotwali", "Moglabazar", "Osmaninagar", "Shah Paran", "Sylhet Sadar", "Zakiganj"],
  "Tangail": ["Basail", "Bhuapur", "Delduar", "Dhanbari", "Ghatail", "Gopalpur", "Kalihati", "Madhupur", "Mirzapur", "Nagarpur", "Sakhipur", "Tangail Sadar"],
  "Thakurgaon": ["Baliadangi", "Haripur", "Pirganj", "Ranisankail", "Thakurgaon Sadar"]
};

export const ALL_DISTRICTS = [
  "Bagerhat", "Bandarban", "Barguna", "Barishal", "Bhola", "Bogura", "Brahmanbaria",
  "Chandpur", "Chapainawabganj", "Chattogram", "Chuadanga", "Cox's Bazar", "Cumilla",
  "Dhaka", "Dinajpur", "Faridpur", "Feni", "Gaibandha", "Gazipur", "Gopalganj",
  "Habiganj", "Jamalpur", "Jashore", "Jhalokati", "Jhenaidah", "Joypurhat", "Khagrachhari",
  "Khulna", "Kishoreganj", "Kurigram", "Kushtia", "Lakshmipur", "Lalmonirhat", "Madaripur",
  "Magura", "Manikganj", "Meherpur", "Moulvibazar", "Munshiganj", "Mymensingh", "Naogaon",
  "Narail", "Narayanganj", "Narsingdi", "Natore", "Netrokona", "Nilphamari", "Noakhali",
  "Pabna", "Panchagarh", "Patuakhali", "Pirojpur", "Rajbari", "Rajshahi", "Rangamati",
  "Rangpur", "Satkhira", "Shariatpur", "Sherpur", "Sirajganj", "Sunamganj", "Sylhet",
  "Tangail", "Thakurgaon"
];
