import fs from 'fs';

const dict = {
  "চলমান ক্যাম্পেইন": "Active Campaigns",
  "অর্ডারসমূহ": "Orders",
  "অ্যানালিটিক্স রিপোর্ট": "Analytics Report",
  "সাপোর্ট": "Support",
  "পণ্য": "Products",
  "ক্যাটাগরি": "Categories",
  "রিফান্ড": "Refunds",
  "ইউজার": "Users",
  "ক্যাম্পেইন": "Campaigns",
  "বাল্ক SMS": "Bulk SMS",
  "হিসাব-নিকাশ": "Accounts",
  "সেটিংস": "Settings",
  "মোট অর্ডার": "Total Orders",
  "পেন্ডিং অর্ডার": "Pending Orders",
  "মোট সেলস": "Total Sales",
  "সাকসেস রেট": "Success Rate",
  "লাস্ট ২৮ দিন": "Last 28 Days",
  "সাম্প্রতিক অর্ডারসমূহ": "Recent Orders",
  "সব": "All",
  "পেন্ডিং": "Pending",
  "কনফার্মড": "Confirmed",
  "শিফট": "Shipped",
  "ডেলিভারড": "Delivered",
  "রিটার্ন": "Returned",
  "ক্যান্সেল": "Cancelled",
  "সব এরিয়া": "All Areas",
  "ইনসাইড ঢাকা": "Inside Dhaka",
  "আউটসাইড ঢাকা": "Outside Dhaka",
  "অজানা ইউজার": "Unknown User",
  "অজানা কাস্টমার": "Unknown Customer",
  "আজ": "Today",
  "আপডেট": "Update",
  "যোগ করুন": "Add",
  "পাবলিশড (ওয়েবসাইটে দেখাচ্ছে)": "Published (Live)",
  "আনপাবলিশড (হাইড করা আছে)": "Unpublished (Hidden)",
  "ফোন নম্বর (2FA)...": "Phone Number (2FA)...",
  "পাসওয়ার্ড...": "Password...",
  "ভুল পাসওয়ার্ড! আবার চেষ্টা করুন।": "Wrong password! Try again.",
  "মুছুন": "Delete",
  "মুছছি...": "Deleting...",
  "অ্যাডমিন": "Admin",
  "মডারেটর": "Moderator",
  "বিস্তারিত অ্যাডমিন": "Detailed Admin",
  "অ্যাডমিন ম্যানেজমেন্ট": "Admin Management",
  "ইউজার অ্যাক্সেস": "User Access",
  "নতুন অ্যাডমিন/মডারেটর যোগ করুন": "Add New Admin/Moderator",
  "অ্যাডমিন/মডারেটর এডিট করুন": "Edit Admin/Moderator",
  "সাধারণ সেটিংস": "General Settings",
  "হোমপেজ ব্যানার": "Homepage Banners",
  "কুরিয়ার সেটিংস (Pathao)": "Courier Settings (Pathao)",
  "কুরিয়ার সেটিংস (Steadfast)": "Courier Settings (Steadfast)",
  "ব্যানার যোগ করুন": "Add Banner",
  "ব্যানার আপডেট করুন": "Update Banner",
  "ব্যানার আপলোড": "Upload Banner",
  "ছবির লিংক দিন (https://...)": "Image Link (https://...)",
  "লিঙ্ক বা প্রোডাক্ট আইডি (Link)": "Link or Product ID",
  "শিরোনাম (Title)": "Title",
  "চালু আছে": "Enabled",
  "বন্ধ আছে": "Disabled",
  "ইমেইল অ্যাড্রেস লিখুন...": "Enter Email Address...",
  "ইমেইল বা ফোন নাম্বার দিয়ে খুঁজুন...": "Search by Email or Phone...",
  "ফোন নাম্বার দিয়ে খুঁজুন...": "Search by Phone Number...",
  "কাস্টমারদের রিফান্ড রিকোয়েস্টগুলো এখানে দেখা যাবে": "Customer refund requests will appear here",
  "এখনো কোনো রিফান্ড রিকোয়েস্ট আসেনি": "No refund requests yet",
  "আপনি কি এই রিফান্ড রিকোয়েস্টটি অ্যাপ্রুভ করতে চান? এটি ইউজারের ব্যালেন্সে টাকা যোগ করে দেবে।": "Approve this refund request? It will add funds to user's balance.",
  "আপনি কি এই রিকোয়েস্টটি রিজেক্ট করতে চান?": "Reject this request?",
  "রিফান্ড রিকুয়েস্ট": "Refund Request",
  "গ্রাহক তালিক?": "Customer List",
  "কোন ডেটা পাওয়া যায়নি": "No data found",
  "কোন ইউজার পাওয়া যায়নি": "No user found",
  "কাস্টমার": "Customer",
  "অ্যাক্সেস": "Access",
  "অ্যাকশন": "Action",
  "ক্যাশ অন ডেলিভারি:": "Cash on Delivery:",
  "হার:": "Rate:",
  "চালু করলে অর্ডার করুন পর কাস্টমার এসএমএস পাবে?": "If enabled, customer will receive SMS after order.",
  "পাঠানো হয়েছে: ": "Sent: ",
  "বাকি: ": "Remaining: ",
  "সফল:": "Success:",
  "ব্যর্থ:": "Failed:",
  "চেকিং...": "Checking...",
  "পাঠানো হচ্ছে...": "Sending...",
  "পাঠিয়ে দিন": "Send Now",
  "মেসেজটি এখানে লিখুন...": "Write your message here...",
  "প্রথম অংশ / শুরুর বার্তা": "First part / Start message",
  "শেষ অংশ / অতিরিক্ত বার্তা": "Last part / Additional message",
  "সকল গ্রাহকের ফোন নাম্বারে Bulk SMS পাঠান": "Send Bulk SMS to all customer phone numbers",
  "নতুন প্রোডাক্ট বা অফারের তথ্য সব গ্রাহককে পাঠান": "Send new product or offer info to all customers",
  "প্রাপক:": "Recipient:",
  "প্রেরক: ": "Sender: ",
  "তারিখ": "Date",
  "ধাপ": "Step",
  "নির্বাচন করুন": "Select",
  "নতুন ক্যাম্পেইন": "New Campaign",
  "এডিট ক্যাম্পেইন": "Edit Campaign",
  "ক্যাম্পেইন নাম": "Campaign Name",
  "যেমন: ঈদ ধামাকা": "e.g. Eid Dhamaka",
  "যেমন: eid-dhamaka": "e.g. eid-dhamaka",
  "ইউনিক হতে হবে। উদা: ?campaign=eid-dhamaka": "Must be unique. e.g. ?campaign=eid-dhamaka",
  "প্রোডাক্ট সিলেক্ট করুন": "Select Products",
  "ক্যাম্পেইনটি লাইভ করুন": "Make Campaign Live",
  "কোনো লিংক নেই": "No link",
  "কোনো নোটিফিকেশন পাওয়া যায়নি": "No notification found",
  "কোনো ক্যাম্পেইন পাওয়া যায়নি": "No campaign found",
  "সব নোটিফিকেশন হিস্ট্রি": "All Notification History",
  "নোটিফিকেশন পাঠান": "Send Notification",
  "ইমেজ আপলোড করুন": "Upload Image",
  "নতুন পণ্য যোগ করুন": "Add New Product",
  "পণ্য যোগ করুন": "Add Product",
  "পণ্য এডিট করুন": "Edit Product",
  "পণ্য সম্পর্কে বিস্তারিত লিখুন...": "Write product details here...",
  "স্টক (Quantity)": "Stock (Quantity)",
  "স্টক সংখ্যা দেখান": "Show Stock Count",
  "মূল্য (Price Per Pc)": "Price (Per Pc)",
  "ন্যূনতম পরিমাণ (Min Qty)": "Minimum Qty",
  "পিস (Piece)": "Piece",
  "কেজি (KG)": "KG",
  "গ্রাম (Gram)": "Gram",
  "লিটার (Liter)": "Liter",
  "মিলি (ML)": "ML",
  "বক্স (Box)": "Box",
  "প্যাকেট (Packet)": "Packet",
  "সেট (Set)": "Set",
  "স্ট্যান্ডার্ড (Default)": "Standard (Default)",
  "খুব বড় (Extra Large)": "Extra Large",
  "বড় (Large)": "Large",
  "ছোট (Small)": "Small",
  "যেমন: XL": "e.g. XL",
  "যেমন: লাল": "e.g. Red",
  "আরও ট্যাগ লিখুন...": "Add more tags...",
  "যেমন: smartwatch, apple watch (কমা বা এন্টার চাপুন)": "e.g. smartwatch, apple watch (Comma or Enter to add)",
  "যেমন: p123": "e.g. p123",
  "e.g. সেরা মানের পণ্য": "e.g. Best quality product",
  "e.g. স্মার্ট ওয়াচ": "e.g. Smart Watch",
  "e.g. স্মার্ট ওয়াচ সিরিজ ৯": "e.g. Smart Watch Series 9",
  "e.g. ১০০% অরিজিনাল পন্যের নিশ্চয়তা": "e.g. 100% Original Product Guarantee",
  "▶ স্টক/করুন? অর্ডার? করুন নিয়ম:": "▶ Stock Rules:",
  "• প্রতিটি সাইজ বা কালারের জন্য আলাদাভাবে স্টক (Quantity) যুক্ত করুন?": "• Add stock separately for each size or color?",
  "• যদি সাইজ বা করুন? না থাকে, তাহলে Size এ": "• If no size, keep Size field empty",
  "🎨 ভেরিয়েন্ট ও সাইজ": "🎨 Variants & Sizes",
  "অর্ডার ID": "Order ID",
  "অসম্পূর্ণ অর্ডারসমূহ": "Incomplete Orders",
  "কোনো অসম্পূর্ণ অর্ডার নেই": "No incomplete orders",
  "কোনো ফোন নাম্বার পাওয়া যায়নি": "No phone number found",
  "কোনো ঠিকানা নেই": "No address found",
  "কোএ¥াও ঠিকানা নেই": "No address",
  "অর্ডার চেকআউটে ক্যাশ অন ডেলিভারি অপশনটি দেখাবে কিনা": "Show Cash on Delivery option at checkout",
  "ক্যাশ অন ডেলিভারি (COD) অপশন": "Cash on Delivery (COD) Option",
  "কাস্টমাররা চেকআউট পেজে এই কোডটি দেখতে পাবে": "Customers will see this code on checkout",
  "কুপন সফলভাবে প্রয়োগ করা হয়েছে! আপনি ফ্রি ডেলিভারি পাচ্ছেন।": "Coupon applied successfully! You get Free Delivery.",
  "আপনার কমেন্ট লিখুন...": "Write your comment...",
  "আপনার মেসেজ লিখুন...": "Write your message...",
  "রিপ্লাই লিখুন...": "Write a reply...",
  "যেমন: কোনো প্রয়োজনে আমাদের সাথে যোগাযোগ করুন: 01777600844": "e.g. Contact us for any query: 01777600844",
  "যেমন: প্রিয় কাস্টমার, আপনার অর্ডারটি অর্ডার হয়েছে?": "e.g. Dear customer, your order has been placed successfully.",
  "যেমন: ধামাকা অফার!": "e.g. Dhamaka Offer!",
  "iShop BD ব্যবহার করার জন্য ধন্যবাদ।": "Thank you for using iShop BD.",
  "প্রিয় গ্রাহক, আপনার অর্ডারটি কনফার্ম হয়েছে।": "Dear customer, your order is confirmed.",
  "সাউন্ড অন করে শুনুন": "Turn on sound to listen",
  "অ্যাডমিন প্যানেল": "Admin Panel",
  "এক্সেল এক্সপোর্ট": "Excel Export",
  "চেক করুন": "Check",
  "পাবলিক করুন": "Make Public",
  "আপডেট টাই?": "Update Time?",
  "১ বছর": "1 Year",
  "৩ বছর": "3 Years",
  "লাইফটাইম": "Lifetime",
  "মোট:": "Total:",
  "সিলেক্টেড": "Selected",
  "বাতিল:": "Cancelled:",
  "মোট চ্যাট": "Total Chats",
  "মোট ইউনিক নম্বর": "Total Unique Numbers",
  "লিখে দিন।": "Write here.",
  "হোয়াটসঅ্যাপ অর্ডার নাম্বার": "WhatsApp Order Number",
  "কনফার্ম এসএমএস চালু": "Confirm SMS Enabled",
  "কনফার্মেশন এসএমএস টেমপ্লেট (স্বয়ংক্রিয় এসএমএস)": "Confirmation SMS Template",
  "/> বেসিক ইনফরমেশন": "/> Basic Information",
  "/> প্রাইসিং ও স্টক": "/> Pricing & Stock",
  "/> মিডিয়া ও এসইও": "/> Media & SEO",
  "পি অর্ডার": "Pre Order",
  "অনর": "Other",
  "করুন? (ঐচ্ছিক)": "Color (Optional)",
  "কান্ট্রি কোড": "Country Code",
  "কুরিয়ার (Steadfast):": "Courier (Steadfast):"
};

let content = fs.readFileSync('src/components/AdminPanel.tsx', 'utf8');

for (const [bn, en] of Object.entries(dict)) {
  // Use global regex replace for literal string
  const regex = new RegExp(bn.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');
  content = content.replace(regex, en);
}

// Write back
fs.writeFileSync('src/components/AdminPanel.tsx', content);
console.log('Translation complete.');
